### ISSUE TITLE
Firepicker box hide

### ISSUE THREAD

**Issue by PawelPatyk** [thedarkone/firepicker#23]
For some time after you edit the color (or add the same value) in the CSS panel, I can no longer edit any other value or add a new one.

In the screenshot you can see an empty field when you click on them (not editable): https://dl.dropbox.com/u/5785988/firebug-bug.png

Firefox: 13 (previous versions, also)
Firebug: 1.10.0a.11 (previous versions, also)
Firepicker: 1.4.1

**Comment by thedarkone** [comment]
What you are describing seems to be pretty random with no way to consistently reproduce, right?

I'm not sure how I'll ever be able to track this down ;(.

**Comment by SebastianZ** [comment]
For reference: This issue was first [mentioned in the Firebug discussion group](https://groups.google.com/d/msg/firebug/JI-wy6X-aWU/U6IT7dcez7MJ).
Pawel, it will help a lot if you can provide a reproducible test case including step by step instructions what to do. Firebug has [some description about how to create one](http://getfirebug.com/wiki/index.php/Creating_a_Test_Case).

Sebastian

**Comment by PawelPatyk** [comment]
Hi,
The error persists on each website.
For example, enter google.com and study in Firebug 'color' for the element 'body'.
The first time it works, but we want to re-edit 'color' (without refreshing the page), the color of the box is empty.

Firefox 15.0.1
Firebug 1.10.3
Firepicker 1.4.1

**Comment by SebastianZ** [comment]
I tried to reproduce that right now using FF 15.0.1 + FB 1.10.3/[1.11a3](https://getfirebug.com/releases/firebug/1.11/firebug-1.11.0a3.xpi) + FP 1.4.1 and I could not reproduce that.

My steps:
1. Installed Firebug and Firepicker on a fresh Firefox profile
2. Opened Firebug on http://google.com
3. Being at the _Style_ side panel I clicked the value of the `color` property inside the `body` rule.
  => The inline editor displayed the value (OK)
4. Changed the color to `#ff0000`
5. Clicked somewhere else to stop inline editing
6. Clicked the value of the `color` property again
  => The inline editor displayed the value again. (OK)

Do you do something else? If not, I guess another extension or a setting could be the culprit.
Therefore please follow the [steps for what to do when you see a bug in Firebug](https://getfirebug.com/wiki/index.php/I_found_a_Firebug_Bug!). Doing so you can probably find out what's causing this.

Sebastian

**Comment by thedarkone** [comment]
@PawelPatyk: could you make sure you are not using the [friendly bug](https://addons.mozilla.org/en-us/firefox/addon/friendly-bug/) plugin? It seems to contain a full copy of the Firepicker which of course results in breakage :(. I've had multiple users' issues fixed by simply uninstalling Friendly bug.

**Comment by PawelPatyk** [comment]
I don't use plugin 'friendly bug'.

@SebastianZ: Fresh Firefox profile - works :)
The default profile turned off all plugins (except FB and FP) and the error still occurred.
I'll try to find the error.

**Comment by SebastianZ** [comment]
> @SebastianZ: Fresh Firefox profile - works :)
> The default profile turned off all plugins (except FB and FP) and the error still occurred.
> I'll try to find the error.

Ok, so it's most likely a specific setting. What happens when you reset the Firebug settings?

Sebastian

**Comment by PawelPatyk** [comment]
Reset Firebug plug-in help.
Thank you!

**Comment by SebastianZ** [comment]
Ok, so it was a Firebug setting causing it. I guess you didn't save your `prefs.js` as described at the page I sent you earlier, did you?

Sebastian

**Comment by PawelPatyk** [comment]
I didn't save <code>prefs.js</code>.

**Comment by thedarkone** [comment]
Well, Firebug is scary complicated. @SebastianZ thanks for the help.

Closing.

**Comment by SebastianZ** [comment]
> Well, Firebug is scary complicated.

That's why we added our ["first aid"](https://getfirebug.com/wiki/index.php/I_found_a_Firebug_Bug!) page. But of course with more and more functionality it's also getting more complex. But feel free to [add any suggestions](http://code.google.com/p/fbug/issues/entry?template=User%20enhancement%20request) how to make it less complicated. :-)

> @SebastianZ thanks for the help.

You're welcome. Now you have time to concentrate on my issues. ;-)

Sebastian

**Comment by thedarkone** [comment]
@SebastianZ is there anything I can do (in Firepicker) to alleviate this `prefs.js` issue? I have others having the same problems [here](https://github.com/thedarkone/firepicker/issues/28) and [here](https://addons.mozilla.org/en-US/firefox/addon/firepicker/reviews/388448/).

**Comment by SebastianZ** [comment]
The point is that we unfortunately didn't get to know which preference(s) cause(s) this behavior. And I couldn't reproduce that earlier.
So the point is to ask the people for the `prefs.js` file. For privacy reasons you should tell them just to send the Firebug and Firepicker relevant parts of it.

Sebastian
